name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python_version: '3.10'

      - name: Install Buildozer
        run: |
          pip install --user buildozer cython==0.29.33
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev Python3 SDL2 ttf-fonts libssl-dev

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Если файла настроек нет, создаем его
          if [ ! -f buildozer.spec ]; then
            buildozer init
            sed -i 's/requirements = python3,kivy/requirements = python3,kivy/' buildozer.spec
          fi
          # Магия сборки (может идти долго!)
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Mobile-Antivirus
          path: bin/*.apk
          
