name: Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python & PyInstaller
        run: |
          pip install pyinstaller
      - name: Make EXE
        run: pyinstaller --noconsole --onefile main.py
      - uses: actions/upload-artifact@v3
        with:
          name: Virus-Scanner-EXE
          path: dist/main.exe
          
